log_dir: logs/
resume:

metrics:
  - _target_: srcs.metrics.accuracy
  - _target_: srcs.metrics.f1
  - _target_: srcs.metrics.g_score

defaults:
  - _self_
  - data: mnist_train
  - model: mnist_lenet
  - tune_scheduler: ASHAScheduler
  - trainer: torch_trainer

  - status: train

  - override hydra/job_logging: custom

hydra:
  run:
    dir: ./outputs/${status}-${name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
