resume:
save_dir: models/
log_dir: ${name}/

metrics:
  - _target_: srcs.metric.accuracy
  - _target_: srcs.metric.top_k_acc

defaults:
  - _self_
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline

  - status: train

  - override hydra/job_logging: custom

hydra:
  run:
    dir: ../outputs/${status}/${now:%Y-%m-%d}/${now:%H-%M-%S}

