resume:
restore:

metrics:
  - _target_: src.metrics.accuracy
  - _target_: src.metrics.f1
  - _target_: src.metrics.g_score

defaults:

  - data_loader: mnist_train
  - model: mnist_lenet
  - tune_scheduler: ASHAScheduler
  - trainer: torch_trainer

  - status: train

  - hydra/run/dir: job_timestamp
  - override hydra/job_logging: custom
  - _self_

trainer:
  run:
    restore: ${restore}

