train_func:
  _target_: srcs.trainer.tune_trainer.train_func
epochs: 100
run:
  metric: val_accuracy
  mode: max
  resources_per_trial:
    cpu: ${n_cpu}
    gpu: ${n_gpu}
  scheduler: ${tune_scheduler}
  verbose: 2