# @package _global_
hp_search:
  _target_: src.model_selection.HPSearch
  verbose: 2
  num_samples: 1
  resources_per_trial:
    cpu: ${cpu_per_task}
    gpu: ${gpu_per_task}
  cv: 5
  seed: ${seed}


defaults:
  - _self_
#  - scheduler: asha_scheduler
  - search_alg: optuna
#  - mixins: wandb